spring:
  application:
    name: dinereserve-auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dinereserve}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1979}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

jwt:
  secret: ${JWT_SECRET:almararmudheyvanarasdafsghfdssfghfdssdsddsdsdsd}
  access-expiration: ${JWT_ACCESS_EXPIRATION:300000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:1800000}

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://dinereserve-discovery-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true


logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG